- simulator: VTD
  ip: 127.0.0.1 # ip of running VTD server
  port: 1337
  input: 
      - {interface_name: a, base_name: b, type: bool} # name and type of VTD variables
      - {interface_name: b, base_name: a, type: double} 
  output:
       - {interface_name: e, base_name: f, type: bool} #name and type of VTD variables
- simulator: FMI
  models: PATH_TO_.ssp # path to model.xml files