- simulator: CARLA
  carla_host: localost
  carla_port: 1337
  client_host: 127.56.0.14
  client_port: 5678
  delta: 0.03
  timeout: 3
- simulator: VTD
  ip: 127.0.0.1 # ip of running VTD server
  port: 1337
  input: 
      - {interface_name: a, base_name: b, type: bool} # name and type of VTD variables
      - {interface_name: b, base_name: a, type: double} 
  output: [] #empty list
- simulator: FMI
  models: PATH_TO_.ssp # path to model.xml files
- simulator: OSMP
  prefix: /#
  input:
      - {interface_name: SensorView, base_name: SensorView}
  output:
      - {interface_name: SensorViewConfiguration, base_name: SensorViewConfiguration}