- simulator: CARLA
  carla_host: localhost
  carla_port: 2000
  client_host: localhost
  client_port: 51425
  delta: 0.03
  transaction_timeout: 3
  do_step_timeout: 30000
  initialisation_timeout: 60000
- simulator: FMI
  model: /Path/to/FMU.fmu # path to model.xml files
- simulator: OSMP
  model: pathToModel
  prefix: "#test#"
  host: localhost
  port: 51426
  transaction_timeout: 5
  do_step_timeout: 5
  input:
      - {interface_name: SensorView, base_name: SensorView1234, default_value: ""}
  output:
      - {interface_name: "SensorData[0]", base_name: SensorData1234, default_value: ""} #type for OSMP is always string
      - {interface_name: "SensorData[1]", base_name: SensorData5678, default_value: ""}