- simulator: "CARLA"
  carla_host: 10.34.99.240
  carla_port: "2000"
  client_host: 0.0.0.0
  client_port: 51425
  delta: 0.03
  transaction_timeout: 30000
  do_step_timeout: 30000
  initialisation_timeout: 600000
- simulator: OSMP
  model: "/setlevel/fmu/OSMPCameraSensor.fmu"
  prefix: "#cosima#"
  host: 0.0.0.0
  #host: 10.34.96.70
  port: 51427
  transaction_timeout: 30000
  # in seconds, may change later to ms too
  do_step_timeout: 30000
  input:
    - {interface_name: "OSMPSensorView", base_name: "OSMPSensorViewGroundTruth"}
  output:
    - {interface_name: "OSMPSensorData", base_name: "OSMPSensorData[1]"}

