- simulator: GENERIC
  delta: 0.03
- simulator: CARLA
  carla_host: localhost
  carla_port: 2000
  client_host: localhost
  client_port: 51425
  transaction_timeout: 30000
  do_step_timeout: 30000
  initialisation_timeout: 60000
- simulator: FMI #local fmi implementation
  model: /Path/to/FMU.fmu
- simulator: OSMP #OSMP-Service
  model: /Path/to/FMU.fmu
  host: localhost
  port: 51426
  transaction_timeout: 5000
  do_step_timeout: 5000
  input:
      - {interface_name: OSMPSensorView, base_name: OSMPSensorViewGroundTruth, default_value: ""}
  output:
      - {interface_name: OSMPSensorData, base_name: OSMPSensorData, default_value: ""}
  parameter: # example for address and port in https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/blob/master/examples/OSMPCNetworkProxy/modelDescription.in.xml
      - {name: address, value: localhost}
	  - {name: port, value: 1234}