- simulator: CARLA
  carla_host: localhost
  carla_port: 2000
  client_host: localhost
  client_port: 51425
  delta: 0.03
  transaction_timeout: 30
  do_step_timeout: 30000
  initialisation_timeout: 60000
- simulator: OSMP
  model: /Path/to/FMU.fmu
  prefix: "#prefix#"
  host: localhost
  port: 51426
  transaction_timeout: 5
  do_step_timeout: 5
  input:
      - {interface_name: OSMPSensorView, base_name: OSMPSensorViewGroundTruth}
  output:
      - {interface_name: "OSMPSensorData", base_name: OSMPSensorData}
