- simulator: CARLA
  carla_host: localhost
  carla_port: 2000
  client_host: localhost
  client_port: 51425
  delta: 0.03
  transaction_timeout: 30000
  do_step_timeout: 30000
  initialisation_timeout: 60000
  sensor_view_config:
    prefixed_fmu_variable_name: "#osi#OSMPSensorViewGroundTruth"
	lidar_sensor_mounting_position:
	 - {x: 2.45, y: -0.35, z: -0.13, roll:0, pitch:0, yaw:0}
- simulator: OSMP
  model: /Path/to/FMU.fmu
  prefix: "#prefix#"
  host: localhost
  port: 51426
  transaction_timeout: 5000
  do_step_timeout: 5000
  input:
      - {interface_name: OSMPSensorView, base_name: OSMPSensorViewGroundTruth}
  output:
      - {interface_name: "OSMPSensorData", base_name: OSMPSensorData}
