- simulator: CARLA
  carla_host: localhost
  carla_port: 1337
  client_host: 127.56.0.14
  client_port: 5678
  delta: 0.03
  timeout: 3
- simulator: OSMP
  model: Path_to_FMU
  prefix: /#
  host: 12.34.56.78
  port: 4711
  transaction_timeout: 0.1
  do_step_timeout: 0.5
  input:
      - {interface_name: SensorView, base_name: SensorView1234}
  output:
      - {interface_name: "SensorData[0]", base_name: SensorData1234}
      - {interface_name: "SensorData[1]", base_name: SensorData5678}